---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: <%= ENV['CHEF_VERSION'] || ':latest' %>
  client_rb:
    chef_license: accept

platforms:
  - name: centos-6.9
  - name: centos-7.4

verifier:
  name: inspec

suites:
  - name: auto-master
    run_list:
      - recipe[kitchen_sudoers::default]
      - recipe[auto_master_test::default]
  - name: map-entry
    run_list:
      - recipe[kitchen_sudoers::default]
      - recipe[map_entry_test::default]
  - name: multi
    run_list:
      - recipe[kitchen_sudoers::default]
      - recipe[multi_test::default]
  - name: nfs
    run_list:
      - recipe[kitchen_sudoers::default]
      - recipe[nfs_test::default]
