AllCops:
  Exclude:
    - .kitchen/**/*
    - Guardfile
    - vendor/**/*
Style/Encoding:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%i": "()"
